# Generated by Django 5.0.4 on 2024-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nationalityID', models.IntegerField()),
                ('birthDate', models.DateTimeField()),
            ],
        ),
    ]
